#+TITLE: 20160622_vmware_shared_folder
#+DATE: <2016-06-22 14:47:42>
#+TAGS:
#+LAYOUT:post
#+CATEGORIES:
#+OPTIONS: toc:nil
#+STARTUP: indent
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{WenQuanYi Micro Hei Mono}
#+BIND: org-html-postamble "<div style='font-size: 14px;padding: 5px;line-height: 20px;border: 1px solid;'> Copyright (c) 2016-2020 %a - Last Updated %C.</br>Render by <a href='https://github.com/CodeFalling/hexo-renderer-org'>hexo-renderer-org</a> with %c</div>"

Here is some text that I want in @@html:<font color = "red">@@BOLD RED@@html:</font>@@
@@html:<span class="label label-success">@@主题配置文件@@html:</span>@@



#+begin_sidebar
*You will learn to:*

- write your docs in Org mode
- create tables
- create custom code blocks
- and much more!
#+end_sidebar

#+begin_abstract
This is an Org mode document, using the ~.org~ extension (supported by GitHub).

#+BEGIN_HTML
<code>warning</code>
#+END_HTML

*Org mode* is an easy-to-write /plain text/ formatting syntax for authoring notes,
articles, LaTeX documents, books, Web pages, Beamer slide decks and much more!

This is a cheat sheet for *Org mode 8* (because of some markup syntax changes
since Org mode 7), using [[https://github.com/fniessen/org-html-themes][ReadTheOrg CSS]].

Reading through all the [[http://orgmode.org/org.pdf][documentation]] is highly recommended, but for the truly
impatient, following are some quick steps to get started.
#+end_abstract

{% textcolor success %}Duis mollis, est non commodo luctus, nisi erat porttitor ligula.{% endtextcolor %}

{% alert warning %}Best check yo self, you're not looking too good.{% endalert %}

{% badge ptth42 info %}

{% btn hahack warning %}

{% btn hahack danger %}

{% btn hahack info %}

{% label danger danger %}

{% label primary primary %}

{% label info info %}

#+BEGIN_HTML
<!--more-->
#+END_HTML


